FROM node:15.2.1-alpine3.10

WORKDIR /upa-ui
ENV PATH /upa-ai/node_modules/.bin:$PATH
COPY ./ui/package.json /upa-ui/
RUN npm install --legacy-peer-deps

COPY ./ui/src/* /upa-ui/src/
COPY ./ui/public/* /upa-ui/public/

ENV REACT_APP_API_URL localhost:8080
ENV REACT_APP_IMPORTER_URL localhost:4200

RUN npm run build

FROM nginx:1.19.4

ENV PORT 80

COPY --from=0 /upa-ui/build/ /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./ui/nginx/nginx.conf /etc/nginx/conf.d/
COPY ./ui/entrypoint.sh /entrypoint.sh

WORKDIR /upa-ui

ENV REACT_APP_API_URL localhost:8080
ENV REACT_APP_IMPORTER_URL localhost:4200

EXPOSE 80
