FROM python:3.8

ENV NOSQL_DBNAME upa-covid19
ENV NOSQL_HOST upa-mongo

ENV SQL_DBNAME upa-covid19
ENV SQL_HOST upa-postgress
ENV SQL_USERNAME upa_importer
ENV SQL_PASSWORD upa_importer_pwd

ENV PYTHONUNBUFFERED 1

WORKDIR /importer

COPY ./importer/*       /importer/
COPY ./importer/views/* /importer/views/

RUN pip3 install pipenv
RUN pipenv install --system --deploy --ignore-pipfile
