FROM postgres:13

ENV POSTGRES_DB upa-covid19
ENV POSTGRES_USER upa_admin
ENV POSTGRES_PASSWORD upa_postgres_pwd
ENV PGUSER upa_admin
ENV PGDATABASE upa-covid19

COPY ./sql/schema.sql /docker-entrypoint-initdb.d/
