FROM golang:1.15.2

ENV NOSQL_DBNAME upa-covid19
ENV NOSQL_HOST upa-mongo

ENV SQL_DBNAME upa-covid19
ENV SQL_HOST upa-postgres
ENV SQL_USERNAME upa_api
ENV SQL_PASSWORD upa_api_pwd

ADD ./api/ /go/src/upa/api/

WORKDIR /go/src/upa/api/

RUN go get -d -v upa/api
RUN go install -v
